#!/bin/sh

# auto packing for iOS
# shell+xcodebuild packing for iOS
# by biostome 2019-5-19

# 说明
# 此脚本目前只针对有工作空间workspace文件的打包。
# 此脚本需要您的项目可以手动打包成功一次，只有xcode手动打包成功过一次，自动打包会省去很多配置内容。
# 此脚本力求最简化配置，最好是只需要配置一处，但目前还是需要配置两处：
    #1：匹配项目目录
    #2：设置Plist文件
# 请全局搜索【配置】配置内容。

# 【配置】项目目录
__workSpace_path="/Users/yingju/Desktop/Change/LSSEasyChat"
__project_path="/Users/yingju/Desktop/Change/LSSEasyChat/wfchat"

#—————————————— 目录地址 --------------
__auto_packing_path="/Users/yingju/Desktop/Change"

# 【检查和配置】请修改Plist/AdHocExportOptionsPlist.plist文件，这个文件可以通过手动打包方式导出一次就会自动生成，复制出来用就可以了，当然也可以自己手动新建。
# 这里用的是adhoc打包方式，需要其他的打包方式请自己生成plist文件。
__export_options_plist="${__auto_packing_path}/Plist/AdHocExportOptionsPlist.plist"

# ipa包到处地址，导出位置是脚本下的ipas目录，没有ipas目录会自动生成
__exportPath="${__auto_packing_path}/ipas"

# 归档archive地址，没有则自动生成
__build_path="${__auto_packing_path}/Build"


#——————————————旧文件删除————————————————
echo "<-----------------🚀旧文件删除🚀------------------->"
if [ -d "${__build_path}" ] ; then
    echo "发现Build文件夹有文件，即将清空文件夹📁"
    rm -rf ${__build_path}/*
fi

if [ -d "${__exportPath}" ] ; then
    echo "发现ipas文件夹有文件，即将清空文件夹📁"
    rm -rf ${__exportPath}/*
fi


#-------------- 打包前准备 -----------------
echo "<-----------------🚀打包前准备🚀------------------->"
# cd 到 projectPath 这个路径
cd ${__workSpace_path}
echo ${__workSpace_path}

# 获取Project名称
__project_name=`ls $__project_path | grep .xcodeproj | sed 's/.xcodeproj//g'`
#__project_name=`find . -name *.xcodeproj | awk -F "[/.]" '{print $(NF-1)}'`
echo ${__project_name}
# 获取workspace名称
__work_space_name="${__project_name}"
## 手动设置Targets
#__targets=("立信")
##设置服务器
#__services=("lx")
##plist文件
#__infoPlists=("LXWildFireChat-Info.plist")

# 手动设置Targets
__targets=( "易聊聊" "尊聊" "发聊" "71聊" "微探" "吉聊" "61聊吧" "C5聊吧" "众聊" "WB聊吧" "微聊" "九州" "91聊吧" "联盟聊吧" "乐博聊吧" "立信"  "聊99" "天下聊吧" "网易聊吧")
#设置服务器
__services=( "yf" "zc" "df" "c71" "7c" "jl" "ly" "cw" "zl" "wbl" "wl" "jz" "jy" "cp" "lb" "lx" "ljj" "tx" "wy")
#plist文件
__infoPlists=( "YLLWildFireChat-Info.plist" "ZCWildFireChat-Info.plist" "DFWildFireChat-Info.plist" "CQYWildFireChat-Info.plist" "QCWildFireChat-Info.plist" "JLWildFireChat-Info.plist" "LYWildFireChat-Info.plist" "CWWildFireChat-Info.plist" "ZLWildFireChat-Info.plist" "WBLWildFireChat-Info.plist" "WLWildFireChat-Info.plist" "JZWildFireChat-Info.plist" "JYWildFireChat-Info.plist" "CPWildFireChat-Info.plist" "LBWildFireChat-Info.plist" "LXWildFireChat-Info.plist" "LJJWildFireChat-Info.plist" "TXWildFireChat-Info.plist" "WYWildFireChat-Info.plist")
## 手动设置Targets
#__targets=( "易聊聊" "尊聊" "发聊" "71聊" "微探" "吉聊" "61聊吧" "C5聊吧" "众聊" "WB聊吧" "微聊" "九州" "91聊吧" "联盟聊吧" "乐博聊吧" "立信"  "聊99" "天下聊吧" "网易聊吧")
##设置服务器
#__services=( "yf" "zc" "df" "c71" "7c" "jl" "ly" "cw" "zl" "wbl" "wl" "jz" "jy" "cp" "lb" "lx" "ljj" "tx" "wy")
##plist文件
#__infoPlists=( "YLLWildFireChat-Info.plist" "ZCWildFireChat-Info.plist" "DFWildFireChat-Info.plist" "CQYWildFireChat-Info.plist" "QCWildFireChat-Info.plist" "JLWildFireChat-Info.plist" "LYWildFireChat-Info.plist" "CWWildFireChat-Info.plist" "ZLWildFireChat-Info.plist" "WBLWildFireChat-Info.plist" "WLWildFireChat-Info.plist" "JZWildFireChat-Info.plist" "JYWildFireChat-Info.plist" "CPWildFireChat-Info.plist" "LBWildFireChat-Info.plist" "LXWildFireChat-Info.plist" "LJJWildFireChat-Info.plist" "TXWildFireChat-Info.plist" "WYWildFireChat-Info.plist")

# 自动设置Targets

# 方式一
#__targets=`xcodebuild -list -project ${__project_name}.xcodeproj -json | awk '/\"schemes/,/],/' | sed s/[[:space:]]//g | sed -e '1d' -e '$d' -e 's/,//g' -e 's/\"//g'`

# 方式二
#__targets=`xcodebuild -list -project ${__project_name}.xcodeproj -json | grep - | sed s/,//g | sed s/\"//g | sed s/[[:space:]]//g`

# 方式四
#__targets=`xcodebuild -list -workspace ${__work_space_name}.xcworkspace | grep [-] | grep -v Pods | sed s/[[:space:]]//g | awk '{{printf"%s ",$0}}'`


#-------------- 检查数据,检查这里待完善 -----------------
echo "<-----------------🚀检查数据🚀------------------->"
echo "方案：${__targets}"


#-------------- 开始打包过程 -----------------
echo "<-----------------🚀开始打包🚀------------------->"
#clean所有target项目
xcodebuild clean -configuration Release -alltargets
__index=0
for scheme in ${__targets[@]}; do

    PlistPath=${__project_path}/WildFireChat/config.plist
    #修改config的服务器平台
    /usr/libexec/PlistBuddy -c "Set :target ${__services[__index]}" "$PlistPath"
    #修改infoPlist的版本号（年月日时分+index）
    info_plist="${__project_path}/InfoPlist/${__infoPlists[__index]}"
    echo "Updating build __services to ${__services[__index]}"
    echo "Updating build __infoPlists to ${__infoPlists[__index]}"
    let __index=$__index+1
    __buildtime=$(date "+%Y%m%d%H%M"$__index)
    if [ $__index -lt 10 ]
     then
    __buildtime=$(date "+%Y%m%d%H%M"0$__index)
    
    fi
    
    echo "Updating build __buildtime to ${__buildtime}"

    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${__buildtime}" "${info_plist}"

    # 编译 ".xcarchive" 文件的存放地址
    __archivePath="${__build_path}/${scheme}"
    echo "<-----------------🚀开始归档archive文件🚀------------------->"
    # 归档 对应手动打包archive（使用workspace）
    xcodebuild archive -workspace ${__work_space_name}.xcworkspace -scheme ${scheme} -configuration Release -archivePath ${__archivePath}.xcarchive
    # 检查是否构建成功
    # xcarchive 实际是一个文件夹不是一个文件所以使用 -d 判断
    if [ -d "${__archivePath}.xcarchive" ] ; then
        echo "项目构建成功 🎉 🎉 🎉"
    else
        echo "项目构建失败 😢 😢 😢"
        exit 1
    fi
    # 生成打包时间
    __time=$(date "+%m-%d_%H-%M  "${__buildtime})
    __ipaName="${scheme}${__buildtime}"
    echo "Updating build __time to ${__ipaName}"
    __ipaNameVersion="${scheme}   ${__buildtime}"

    echo ${__ipaNameVersion} >> ${__auto_packing_path}/version.txt

    # 拼接导出ipa的地址
    __ipaPath="${__exportPath}/${__ipaName}"
    echo "<-----------------🚀开始导出ipa文件🚀------------------->"
    # 对应导出步骤
    xcodebuild -exportArchive -archivePath ${__archivePath}.xcarchive -exportPath ${__ipaPath} -exportOptionsPlist ${__export_options_plist}

    if [ -d "${__ipaPath}" ] ; then
        echo "导出 ${__ipaName}.ipa 包成功 🎉 🎉 🎉"
    else
        echo "导出 ${__ipaName}.ipa 包失败 😢 😢 😢"
    fi
#    curl -F 'file=@'${__ipaPath}'' -F '_api_key='${api_key}'' https://www.pgyer.com/apiv2/app/upload

done

echo "<-----------------结束------------------->"
echo "打包总耗时: ${SECONDS}s"
